### PR TITLE
Compatibility with Nette 2.4 (Nette\Object vs. Nette\SmartObject)

### PR DESCRIPTION
**Pull request by miloslavkostir**
**Nette 2.4.x**   
`Echo511\Plupload\SmartObject` is alias of `Nette\SmartObject` and `Echo511\Plupload\LegacyObject` is alias of empty class.

**Older Nette (`Nette\SmartObject` doesn't exists)**   
 `Echo511\Plupload\SmartObject` is alias empty trait but `Echo511\Plupload\LegacyObject` is alias of `Nette\Object`

This solves User Deprecated error in Nette 2.4 and ensures compatibility with older Nette.

### CODE REVIEW

**Comment by echo511** [comment]
I don't like it. It reminds me the Wizard of Oz. I believe the code does not require usage of SmartObject magic. Could you please remove the extends clauses and test the upload? If everything works I'll tag it as `2.2.0`. Thanks.

**Comment by miloslavkostir** [comment]
I don't like it too. But it preserves compatibility with usage of `Nette\Object` (there is extension in `v2.1.1`). Deleting extension of `Nette\Object` and trait of `Nette\SmartObject` will break backward compatibility with `v2.1.1` - I (and probably more people) use in projects e.g. `$uploadEntity->filename`.

Wouldn't be better remove the extends / trait clauses, change composer dependencies `"php": ">=5.6.0"` and `"nette/utils": ">=2.5"` and tag it as `3.0.0`? And then support only new 3.x.x version?

**Comment by miloslavkostir** [comment]
It's not necessary to change composer dependencies, i think. Do it if you want. 

I deleted extensions of `Nette\Object` and traits. Now you can tag new version `3.0.0`.

**Comment by echo511** [comment]
Thank you.

**Pull request merged**
